version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "1337:1337"
    volumes:
      - ./backend/src:/app/src
      - ./backend/index.html:/app/index.html
